version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:10.16.2
    environment:
      NODE_ENV: development

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "yarn.lock" }}
            - v1-node-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v1-node-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/
      - persist_to_workspace:
          paths:
            - ./*
          root: .

  test:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: .
      - run: yarn test

workflows:
  version: 2

  test:
    jobs:
      - setup
      - test:
          requires:
            - setup
