name: Node.js CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]
    tags: ['!*']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm format-check

  test:
    name: Testing ${{ matrix.name }} presets
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        name: [automerge, base, default, docker]

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
        env:
          RENOVATE_CONFIG_FILE: ${{ matrix.name }}.json
