name: Node.js CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile
      - run: yarn format-check
      - run: yarn test
        env:
          RENOVATE_CONFIG_FILE: default.json
